[workspace]
members = [ "src/example","src/testify", "src/testify_core", "src/testify_macros"]
resolver = "3"

[workspace.metadata.release]
shared-version = true
publish = true
tag = true
pre-release-commit-message = "chore: 🔖 Bump version to {{version}}."
